starman:
	sudo cp -a -R starman.d /service/starman
	sudo chmod +t /service/starman
	sudo chown -R logadmin:logadmin /service/starman/log

gracer:
	sudo cp -a -R gracer.d /service/gracer
	sudo chmod +t /service/gracer
	sudo chown -R logadmin:logadmin /service/gracer/log
