starman:
	sudo cp -a -R starman.d /service/starman
	sudo chmod +t /service/starman
	sudo chown -R logadmin:logadmin /service/starman/log

gracer:
	sudo cp -a -R gracer.d /service/gracer
	sudo chmod +t /service/gracer
	sudo chown -R logadmin:logadmin /service/gracer/log

memcached:
	sudo cp -a -R memcached.d /service/memcached
	sudo chmod +t /service/memcached
	sudo chown -R logadmin:logadmin /service/memcached/log

update_stock:
	sudo cp -a -R update_stock.d /service/update_stock
	sudo chmod +t /service/update_stock
	sudo chown -R logadmin:logadmin /service/update_stock/log
